<a href="https://colab.research.google.com/github/yenngocduong/Sign-language-interpreter/blob/main/Convert_NaN_to_Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Convert NaN Values to 0 Values**

Reasoning: [insert desc.]

<br>

In [ ]:
from google.colab import drive # Mount Google Drive to ready access
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import os

array_list = os.listdir('/content/drive/My Drive/EE8101_Deep_Learning/Vid_to_np_array/') # Import numpy array
array_list = sorted(array_list)
len(array_list) # Should be the same as no. of .mp4 videos = 17875

17875

##**Test NaN Value Conversion & File Saving**

Utilising "00295_a.npy" as a test file:

In [ ]:
for array in array_list[:1]: # Loads individual arrays

  nan_array = np.load("/content/drive/MyDrive/EE8101_Deep_Learning/Vid_to_np_array/" + array)
  print(array, "- successfully loaded", end = '\n\n') 
  print(nan_array) 

  num_array = np.nan_to_num(nan_array) # Converts NaN values to 0 values
  print(num_array)
  print(array, "- successfully converted", end = '\n\n') 

  np.save("/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/" + array, num_array)   # Save numpy file to appropriate Google Drive Folder
  print(array, "- successfully saved")

00295_a.npy - successfully loaded

[[[[ 2.39173457e-01  6.72451258e-01 -3.21984298e-05]
   [ 2.67859906e-01  6.41050994e-01 -1.41881099e-02]
   [ 2.88754940e-01  5.92619777e-01 -2.41917260e-02]
   ...
   [ 2.04837188e-01  5.48323452e-01 -7.29365125e-02]
   [ 2.15495735e-01  5.76515555e-01 -7.40801618e-02]
   [ 2.17770800e-01  6.00209355e-01 -7.00127631e-02]]

  [[            nan             nan             nan]
   [            nan             nan             nan]
   [            nan             nan             nan]
   ...
   [            nan             nan             nan]
   [            nan             nan             nan]
   [            nan             nan             nan]]]


 [[[ 2.39364684e-01  6.72565877e-01 -3.05471331e-05]
   [ 2.67917365e-01  6.41028404e-01 -1.42814433e-02]
   [ 2.88576514e-01  5.92623889e-01 -2.40088515e-02]
   ...
   [ 2.04494148e-01  5.48198104e-01 -7.11798444e-02]
   [ 2.14972585e-01  5.76077998e-01 -7.21337348e-02]
   [ 2.17324853e-01  5.99532843e-01 -

##**Checking "00295_a.npy" as converted numpy array:**

In [ ]:
test_array = os.listdir('/content/drive/My Drive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/') # Import numpy array
print(np.load("/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/" + test_array[0]))

[[[[ 2.39173457e-01  6.72451258e-01 -3.21984298e-05]
   [ 2.67859906e-01  6.41050994e-01 -1.41881099e-02]
   [ 2.88754940e-01  5.92619777e-01 -2.41917260e-02]
   ...
   [ 2.04837188e-01  5.48323452e-01 -7.29365125e-02]
   [ 2.15495735e-01  5.76515555e-01 -7.40801618e-02]
   [ 2.17770800e-01  6.00209355e-01 -7.00127631e-02]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]]


 [[[ 2.39364684e-01  6.72565877e-01 -3.05471331e-05]
   [ 2.67917365e-01  6.41028404e-01 -1.42814433e-02]
   [ 2.88576514e-01  5.92623889e-01 -2.40088515e-02]
   ...
   [ 2.04494148e-01  5.48198104e-01 -7.11798444e-02]
   [ 2.14972585e-01  5.76077998e-01 -7.21337348e-02]
   [ 2.17324853e-01  5.99532843e-01 -6.78401068e-02]]

  [[ 0.00000000e+

##**Actual Conversion**

In [ ]:
for array in array_list: # Loads individual arrays

  nan_array = np.load("/content/drive/MyDrive/EE8101_Deep_Learning/Vid_to_np_array/" + array) 

  num_array = np.nan_to_num(nan_array) # Converts NaN values to 0 values
  print(array + " done!")
  #print(num_array)
  #print(array, "- successfully converted", end = '\n\n') 

  np.save("/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/" + array, num_array)   # Save numpy file to appropriate Google Drive Folder
  print(array, "- successfully saved")

Streaming output truncated to the last 5000 lines.
64387_you.npy done!
64387_you.npy - successfully saved
64388_you.npy done!
64388_you.npy - successfully saved
64389_you.npy done!
64389_you.npy - successfully saved
64391_you.npy done!
64391_you.npy - successfully saved
64401_young.npy done!
64401_young.npy - successfully saved
64411_young.npy done!
64411_young.npy - successfully saved
64413_young.npy done!
64413_young.npy - successfully saved
64414_young.npy done!
64414_young.npy - successfully saved
64415_young.npy done!
64415_young.npy - successfully saved
64416_young.npy done!
64416_young.npy - successfully saved
64417_young.npy done!
64417_young.npy - successfully saved
64419_young.npy done!
64419_young.npy - successfully saved
64423_your.npy done!
64423_your.npy - successfully saved
64427_your.npy done!
64427_your.npy - successfully saved
64428_your.npy done!
64428_your.npy - successfully saved
64429_your.npy done!
64429_your.npy - successfully saved
64430_your.npy done!
64430_yo

##**Print dimension**

In [ ]:
from google.colab import drive # Mount Google Drive to ready access
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os

path = "/content/drive/MyDrive/EE8101_Deep_Learning/NaN_to_Zero_Arrays/"

Mounted at /content/drive


In [ ]:
name = "00429_above.npy"
x = np.load(path + name)
x.shape

(50, 2, 21, 3)

In [ ]:
print(x[10])


[[[ 6.01557374e-01  6.64448082e-01 -4.71398789e-06]
  [ 5.90107560e-01  6.21032000e-01  1.25052873e-02]
  [ 5.69486678e-01  5.93821764e-01  3.04395915e-03]
  [ 5.54044604e-01  5.73391020e-01 -1.08385207e-02]
  [ 5.46569407e-01  5.58463931e-01 -2.66894735e-02]
  [ 5.58004677e-01  5.83789170e-01 -2.45102830e-02]
  [ 5.24811685e-01  5.86175740e-01 -4.80202250e-02]
  [ 5.03158808e-01  5.93482375e-01 -6.01673611e-02]
  [ 4.84139472e-01  5.96114933e-01 -6.44825175e-02]
  [ 5.63241601e-01  5.99100471e-01 -4.21209335e-02]
  [ 5.26805758e-01  6.04457080e-01 -6.93866238e-02]
  [ 5.02328038e-01  6.08380258e-01 -8.33997503e-02]
  [ 4.79148805e-01  6.11946583e-01 -9.25925598e-02]
  [ 5.69554269e-01  6.18640840e-01 -5.80548830e-02]
  [ 5.34946442e-01  6.20748758e-01 -8.03368092e-02]
  [ 5.11916041e-01  6.22773647e-01 -8.32108334e-02]
  [ 4.91511405e-01  6.24849498e-01 -8.53746459e-02]
  [ 5.76908827e-01  6.40574574e-01 -7.29184747e-02]
  [ 5.50794244e-01  6.38558030e-01 -8.49543810e-02]
  [ 5.348194

In [ ]:
temp = (np.reshape(x, (len(x), 126))).tolist()
print(len(temp), len(temp[0]))
print(temp[10])

50 126
[0.6015573740005493, 0.664448082447052, -4.713987891591387e-06, 0.5901075601577759, 0.6210319995880127, 0.012505287304520607, 0.569486677646637, 0.5938217639923096, 0.0030439591500908136, 0.5540446043014526, 0.5733910202980042, -0.010838520713150501, 0.5465694069862366, 0.5584639310836792, -0.026689473539590836, 0.5580046772956848, 0.5837891697883606, -0.024510283023118973, 0.5248116850852966, 0.5861757397651672, -0.04802022501826286, 0.5031588077545166, 0.5934823751449585, -0.06016736105084419, 0.48413947224617004, 0.5961149334907532, -0.06448251754045486, 0.5632416009902954, 0.5991004705429077, -0.042120933532714844, 0.5268057584762573, 0.6044570803642273, -0.06938662379980087, 0.5023280382156372, 0.6083802580833435, -0.08339975029230118, 0.479148805141449, 0.6119465827941895, -0.09259255975484848, 0.5695542693138123, 0.6186408400535583, -0.058054883033037186, 0.5349464416503906, 0.62074875831604, -0.0803368091583252, 0.5119160413742065, 0.6227736473083496, -0.0832108333706855